import requests


OLLAMA_URL = "http://localhost:11434/api/chat"
MODEL = "llama3.2"


def generate_ai_explanation(
    eligibility,
    emi_result,
    recommendations,
    user_question=""
):
    if recommendations.empty:
        recommended_product = "No matching synthetic loan product"
    else:
        top_product = recommendations.iloc[0]
        recommended_product = (
            f"{top_product['product_name']} "
            f"at an illustrative interest rate of "
            f"{top_product['interest_rate']}%"
        )

    system_prompt = """
You are an AI financial guidance assistant inside a student-built
loan-assistance product prototype.

Your job is to explain results generated by a deterministic Python
financial calculation engine.

IMPORTANT RULES:
1. Never approve or reject a real loan.
2. Never claim that the user will definitely receive a loan.
3. Never change, recalculate, or reinterpret the numerical results.
4. Treat all supplied EMI, repayment, interest, eligibility and risk
   values as authoritative outputs from the calculation engine.
5. Do not invent missing financial information.
6. Explain the supplied results in simple language.
7. Always make clear that this is an illustrative prototype and not
   an actual lender decision.
8. When explaining EMI, say that the EMI was calculated by the
   deterministic loan calculation engine using the loan amount,
   interest rate and tenure. Do not describe EMI as simply
   "total repayment divided by number of months."
"""

    user_prompt = f"""
Here are the results produced by the deterministic system:

Eligibility score: {eligibility['score']}%
Risk level: {eligibility['risk']}
Passes all prototype checks: {eligibility['eligible']}

Estimated monthly EMI: ₹{emi_result['emi']:,.0f}
Estimated total repayment: ₹{emi_result['total_payment']:,.0f}
Estimated total interest: ₹{emi_result['total_interest']:,.0f}

Recommended synthetic product:
{recommended_product}

User question:
{user_question}

Answer the user's question in 3-5 clear sentences.
"""

    payload = {
        "model": MODEL,
        "messages": [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ],
        "stream": False
    }

    try:
        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        return data["message"]["content"]

    except Exception as e:
        return (
            "The local AI assistant could not connect to Ollama. "
            "Please make sure Ollama is running. "
            f"Error: {e}"
        )